id = "zed-java"
name = "Language support for Java for Zed"
version = "0.0.1"
schema_version = 1
authors = ["yangbaopan@qq.com", "yangbaopan@gmail.com"]
description = "Language support for Java for Zed(Eclipse JDTLS)"
repository = "https://github.com/Carson-yy/zed-java.git"

[grammars.java]
repository = "https://github.com/tree-sitter/tree-sitter-java"
commit = "953abfc8bb3eb2f578e1f461edba4a9885f974b8"

[language_servers.java]
language = "Java"
name = "Eclipse JDTLS"
